#!/usr/bin/env python3
"""
Module:  measure_vault_recall.py
Purpose: Measure how often `tools/knowledge_vault.find_notes` resolves a note from the name
         LB actually says, and how much of the gap two candidate changes would close.
Author:  LB
Date:    2026-08-30

    python media/scripts/measure_vault_recall.py

Writes `media/data/2026-08-30-vault-recall.csv`.

## What is being measured

`find_notes` is the free path. When it returns exactly one note LB gets his own words back for
nothing; when it returns zero the turn either dies or escalates to a paid agent that then has
to search. So every miss here is either a wrong answer or a Gemini request, and that is what
makes this worth a number rather than an opinion.

The three tiers it already has (exact stem, substring stem, >=2-word overlap) all read ONE
string: the filename, plus the folder name. Nothing in the resolver ever opens the file. Both
candidates below are about giving it more strings to match against; neither touches the tiers
themselves and neither requires editing a single note.

## REAL vs SYNTHETIC, kept apart on purpose

`config/oddball.toml` records what it cost to calibrate the wake threshold against a fixture
set that contained no marginal calls: every threshold derived from it was tuned to LB's best
day. The same trap is open here — it is very easy to invent note names that happen to match
the files.

So the phrase set is split and scored separately. **REAL** phrases were transcribed from
`data/oddball.log` and from the capture filenames in `captures/`; they are what he said, typos
of Whisper's included. **SYNTHETIC** phrases are plausible and are NOT evidence. The REAL
column is the one that means anything, and it is small — six phrases — which is itself the
finding: this needs more real material before any threshold-like decision is taken from it.

## The two candidates

- **alnum** — split a letter/digit boundary into two words, both in the query and in the
  filename, so `EEGR105.md` and the spoken "EEGR 105" reduce to the same two words. Today they
  do not, and a course note generated by `tools/syllabus_to_vault.py` cannot be reached by
  voice using its own course code.
- **title** — additionally let a note be found by its own `# H1` heading and by an `aliases:`
  frontmatter list. Costs nothing in the vault as it stands: `syllabus_to_vault.py` already
  writes an H1 naming the course in full, so `POSC201.md` already carries the words "American
  National Government" and no query can currently use them.

Both are simulated HERE, against the live vault, without modifying `tools/knowledge_vault.py`.
Same convention as `measure_kicad_parser.py`: the comparison column is executed, not recalled.
"""

from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from tools.knowledge_vault import (VAULT_DIR, _MIN_OVERLAP, _WEAK_WORDS,  # noqa: E402
                                   _folder_of, _plain, find_notes, notes)

OUT_CSV = REPO / "media" / "data" / "2026-08-30-vault-recall.csv"

# (phrase, source, the note stem it should resolve to, or "" for "nothing, correctly")
#
# REAL: transcribed from data/oddball.log and the capture filenames in captures/. Whisper's
# mistakes are preserved — "read me back the notes that you have for" is what base.en produced
# and is therefore what the resolver actually has to survive.
PHRASES: tuple[tuple[str, str, str], ...] = (
    ("can you add to my note about the topic for my english research paper",
     "REAL", "english research question"),
    ("can you add to my note to my english research paper note thats in the vault",
     "REAL", "english research question"),
    ("whats the topic of my english research paper from my notes",
     "REAL", "english research question"),
    ("read me back the notes that you have for me", "REAL", ""),
    ("tell me what notes you have saved for me", "REAL", ""),
    ("whats on my schedule for today", "REAL", ""),

    # SYNTHETIC. Plausible, unverified, and not evidence for any decision.
    ("my english paper topic", "SYNTHETIC", "english research question"),
    ("the english paper", "SYNTHETIC", "english research question"),
    ("my research question", "SYNTHETIC", "english research question"),
    ("robot arm", "SYNTHETIC", "robot_arm"),
    ("the robot arm project", "SYNTHETIC", "robot_arm"),
    ("my servo note", "SYNTHETIC", "robot_arm"),
    ("EEGR 105", "SYNTHETIC", "EEGR105"),
    ("eegr105", "SYNTHETIC", "EEGR105"),
    ("my EEGR 105 syllabus", "SYNTHETIC", "EEGR105"),
    ("my intro to electrical engineering class", "SYNTHETIC", "EEGR105"),
    ("posc 201", "SYNTHETIC", "POSC201"),
    ("my american government class", "SYNTHETIC", "POSC201"),
    ("peanut butter", "SYNTHETIC", "peanut_butter"),
    ("scratch", "SYNTHETIC", "scratch"),
)

# ------------------------------------------------------------------------------------------
# Candidate 1: alnum — a letter/digit boundary is a word boundary.
# ------------------------------------------------------------------------------------------

_ALNUM_EDGE = re.compile(r"(?<=[A-Za-z])(?=\d)|(?<=\d)(?=[A-Za-z])")


def _split_alnum(text: str) -> str:
    """`EEGR105` -> `EEGR 105`. Already-spaced input is unchanged, so both spellings meet."""
    return _ALNUM_EDGE.sub(" ", text)


# ------------------------------------------------------------------------------------------
# Candidate 2: title — a note may also be named by its own H1 and by `aliases:` frontmatter.
# ------------------------------------------------------------------------------------------

_H1 = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)
_FRONTMATTER = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)
_ALIAS_LINE = re.compile(r"^aliases:\s*\[(.*?)\]\s*$", re.MULTILINE | re.IGNORECASE)


def _declared_names(path: Path) -> list[str]:
    """Every name a note declares about ITSELF: its `aliases:` list, then its first H1.

    Reads at most the head of the file. The H1 is free — `tools/syllabus_to_vault.py` already
    writes one naming the course in full — and `aliases:` is the part LB would have to add,
    which is why they are measured together and reported apart.
    """
    try:
        head = path.read_text(encoding="utf-8")[:2000]
    except OSError:
        return []

    out: list[str] = []
    front = _FRONTMATTER.search(head)
    if front:
        alias = _ALIAS_LINE.search(front.group(1))
        if alias:
            out += [a.strip().strip("\"'") for a in alias.group(1).split(",") if a.strip()]
    title = _H1.search(head)
    if title:
        # "EEGR 105 — INTRODUCTION TO ELECTRICAL ENGINEERING" is two names, not one: the code
        # and the subject. An em-dash split gives both to the overlap tier.
        out += [part.strip() for part in re.split(r"\s[—–-]\s", title.group(1)) if part.strip()]
    return out


def candidate_find(name: str, use_title: bool) -> list[Path]:
    """`find_notes` re-run over a wider set of names per note. Same three tiers, same contract."""
    needle = _plain(_split_alnum(name))
    if not needle:
        return []

    def names_of(path: Path) -> list[str]:
        raw = [path.stem, f"{_folder_of(path)} {path.stem}"]
        if use_title:
            raw += _declared_names(path)
        return [n for n in (_plain(_split_alnum(r)) for r in raw) if n]

    exact = [p for p in notes() if needle in names_of(p)]
    if exact:
        return exact
    partial = [p for p in notes() if any(needle in n for n in names_of(p))]
    if partial:
        return partial

    wanted = {w for w in needle.split() if w not in _WEAK_WORDS}
    if len(wanted) < _MIN_OVERLAP:
        return []
    scored = []
    for path in notes():
        against = {w for n in names_of(path) for w in n.split() if w not in _WEAK_WORDS}
        shared = wanted & against
        if len(shared) >= _MIN_OVERLAP:
            scored.append((len(shared), path))
    if not scored:
        return []
    best = max(s for s, _ in scored)
    return [p for s, p in scored if s == best]


def verdict(found: list[Path], want: str) -> str:
    """RESOLVED / MISS / AMBIGUOUS / WRONG. `want == ""` means "nothing" is the right answer."""
    if not want:
        return "RESOLVED" if not found else "WRONG"
    if not found:
        return "MISS"
    if len(found) > 1:
        return "AMBIGUOUS"
    return "RESOLVED" if found[0].stem == want else "WRONG"


def main() -> int:
    print(f"vault = {VAULT_DIR}  ({len(notes())} notes)\n")

    rows = []
    for phrase, source, want in PHRASES:
        row = {
            "phrase": phrase,
            "source": source,
            "expected": want or "(nothing)",
            "now": verdict(find_notes(phrase), want),
            "alnum": verdict(candidate_find(phrase, use_title=False), want),
            "title": verdict(candidate_find(phrase, use_title=True), want),
        }
        rows.append(row)
        print(f"  {row['source']:<9} {phrase[:52]:<54} "
              f"now={row['now']:<9} alnum={row['alnum']:<9} title={row['title']}")

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_CSV, "w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)

    print()
    for source in ("REAL", "SYNTHETIC", "ALL"):
        subset = [r for r in rows if source in (r["source"], "ALL")]
        line = f"  {source:<10} n={len(subset):<3}"
        for column in ("now", "alnum", "title"):
            ok = sum(1 for r in subset if r[column] == "RESOLVED")
            line += f"  {column}={ok}/{len(subset)}"
        print(line)
    print(f"\n  wrote {OUT_CSV.relative_to(REPO).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
