#!/usr/bin/env python3
"""
Module:  index_tasks.py
Purpose: Put a contents block at the top of tasks/todo.md and tasks/lessons.md, and keep it true.
Author:  LB
Date:    2026-09-06

    python tools/index_tasks.py            # rewrite both index blocks
    python tools/index_tasks.py --check    # fail if either is stale, change nothing
    python tools/index_tasks.py --open     # just print what is still open, newest stage first

## The problem this solves

`tasks/todo.md` is 3,800 lines across 12 stages holding **154 unticked boxes**, and
`tasks/lessons.md` is 52 numbered lessons. Both are append-only by design — this project keeps
dead ends on the record rather than deleting them — so they only ever grow, and the useful
question ("what is still open?") got harder to answer every week.

Scrolling is not the answer and a hand-written contents list is worse: it goes stale silently,
which is the failure mode this repo already has opinions about. So the block is GENERATED,
sits between markers, and `--check` makes staleness visible.

## Why the open count is the headline

A stage index alone would just be 12 links. What LB actually wants on opening the file is
which stages still owe him something, so each row carries its unticked count and the rows with
none are dimmed to a tick. That turns "somewhere in 3,800 lines" into a number per stage.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
TODO = REPO / "tasks" / "todo.md"
LESSONS = REPO / "tasks" / "lessons.md"

START = "<!-- INDEX:START — generated by tools/index_tasks.py. Do not edit by hand. -->"
END = "<!-- INDEX:END -->"

# A heading line, capturing its level and text.
_HEADING = re.compile(r"^(#{1,2}) +(.*?)\s*$")
_OPEN_BOX = re.compile(r"^\s*- \[ \]")
_DONE_BOX = re.compile(r"^\s*- \[x\]", re.I)


def anchor(text: str) -> str:
    """GitHub's heading-to-anchor rule: lowercase, drop punctuation, spaces become hyphens.

    Kept deliberately close to GitHub's own behaviour rather than invented, because a contents
    block whose links do not land is worse than no contents block — it looks navigable and is
    not.
    """
    slug = text.strip().lower()
    slug = re.sub(r"[`*_\[\]()<>.,:;!?/\\'\"’“”]", "", slug)
    slug = re.sub(r"[^\w\s-]", "", slug)          # em dashes, arrows, everything else
    # Each space becomes a hyphen; runs are NOT collapsed. "notebook - dictate" with an em
    # dash removed leaves two spaces and GitHub emits "notebook--dictate". Collapsing here
    # produced links that looked right and landed nowhere.
    return slug.strip().replace(" ", "-")


def _strip_index(text: str) -> str:
    """The file without its generated block, so regenerating is idempotent."""
    if START in text and END in text:
        head, _, rest = text.partition(START)
        _, _, tail = rest.partition(END)
        return head.rstrip("\n") + "\n" + tail.lstrip("\n")
    return text


def _sections(text: str, level: int) -> list[dict]:
    """Every heading at `level`, with the checkbox tallies that belong to it."""
    out: list[dict] = []
    for line in text.splitlines():
        hit = _HEADING.match(line)
        if hit and len(hit.group(1)) == level:
            out.append({"title": hit.group(2), "open": 0, "done": 0, "subs": []})
        elif hit and level == 1 and len(hit.group(1)) == 2 and out:
            out[-1]["subs"].append({"title": hit.group(2), "open": 0, "done": 0})
        elif out:
            target = out[-1]["subs"][-1] if out[-1].get("subs") else out[-1]
            if _OPEN_BOX.match(line):
                target["open"] += 1
                out[-1]["open"] += 1 if target is not out[-1] else 0
            elif _DONE_BOX.match(line):
                target["done"] += 1
                out[-1]["done"] += 1 if target is not out[-1] else 0
    return out


def todo_index(text: str) -> str:
    stages = _sections(text, level=1)
    total_open = sum(s["open"] for s in stages)
    lines = [
        START,
        "",
        f"## Contents — {len(stages)} stages, **{total_open} still open**",
        "",
        "| | Stage | Open | Done |",
        "|---|---|---:|---:|",
    ]
    for s in stages:
        mark = "" if s["open"] else "OK"
        title = s["title"]
        lines.append(f"| {mark} | [{title}](#{anchor(title)}) | "
                     f"{s['open'] or ''} | {s['done'] or ''} |")
        # Stages 1-15 live as `## Stage N` under the first `#` heading, so a top-level-only
        # index would file 118 open items under one row and help nobody.
        for sub in s.get("subs", []):
            if not sub["open"] and not sub["done"]:
                continue
            submark = "" if sub["open"] else "OK"
            lines.append(f"| {submark} | &nbsp;&nbsp;&nbsp;&nbsp;[{sub['title']}]"
                         f"(#{anchor(sub['title'])}) | {sub['open'] or ''} | "
                         f"{sub['done'] or ''} |")
    lines += ["", f"*Regenerate with `python tools/index_tasks.py`.*", "", END]
    return "\n".join(lines)


_LESSON = re.compile(r"^(L\d+)\s*[-–—]\s*(.+)$")


def lessons_index(text: str) -> str:
    """Only the `## Ln` headings. The file also carries a few prose subheadings, and listing
    those among the rules makes the index read as if it had gaps in the numbering."""
    lessons = [m for m in (_LESSON.match(h["title"]) for h in _sections(text, level=2)) if m]
    lines = [START, "", f"## Contents — {len(lessons)} lessons", ""]
    for m in lessons:
        # Separator is an em dash in this file, not a hyphen. Splitting on " - " matched
        # nothing and printed every title twice.
        lines.append(f"- **[{m.group(1)}](#{anchor(m.group(0))})** {m.group(2)}")
    lines += ["", f"*Regenerate with `python tools/index_tasks.py`.*", "", END]
    return "\n".join(lines)


def _rebuild(path: Path, builder) -> tuple[str, str]:
    """Returns (current text, text with a fresh index)."""
    current = path.read_text(encoding="utf-8")
    body = _strip_index(current)

    # The index goes after the title and its blurb, before the first real section.
    lines = body.splitlines()
    insert_at = 1
    for i, line in enumerate(lines[1:], start=1):
        if line.startswith(("# ", "## ", "---")):
            insert_at = i
            break
    else:
        insert_at = len(lines)

    head = "\n".join(lines[:insert_at]).rstrip("\n")
    tail = "\n".join(lines[insert_at:]).lstrip("\n")
    fresh = f"{head}\n\n{builder(body)}\n\n{tail}\n"
    return current, fresh


def main(argv: list[str] | None = None) -> int:
    # `--open` prints todo items verbatim, and they contain arrows and em dashes. A Windows
    # console in its default code page raises UnicodeEncodeError on those, so this tool needs
    # the same stdout fix every harness needs — and there is now one copy of it to call.
    sys.path.insert(0, str(REPO))
    from tools.harness_lib import bootstrap                           # noqa: PLC0415
    bootstrap()

    ap = argparse.ArgumentParser(description="index tasks/todo.md and tasks/lessons.md")
    ap.add_argument("--check", action="store_true", help="fail if an index is stale")
    ap.add_argument("--open", action="store_true", help="list what is still open")
    args = ap.parse_args(argv)

    if args.open:
        body = _strip_index(TODO.read_text(encoding="utf-8"))
        stage = ""
        for line in body.splitlines():
            hit = _HEADING.match(line)
            if hit and len(hit.group(1)) == 1:
                stage = hit.group(2)
            elif _OPEN_BOX.match(line):
                item = re.sub(r"^\s*- \[ \]\s*", "", line)
                item = re.sub(r"\*\*(.+?)\*\*", r"\1", item)
                print(f"  {stage[:34]:36s} {item[:84]}")
        return 0

    stale = []
    for path, builder in ((TODO, todo_index), (LESSONS, lessons_index)):
        current, fresh = _rebuild(path, builder)
        if current == fresh:
            print(f"  {path.relative_to(REPO)}: index current")
            continue
        if args.check:
            stale.append(path)
            print(f"  {path.relative_to(REPO)}: INDEX IS STALE")
        else:
            path.write_text(fresh, encoding="utf-8")
            print(f"  {path.relative_to(REPO)}: index rewritten")

    if stale:
        print("\n  run `python tools/index_tasks.py` to refresh")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
